def test_004_take_out_loan_2000(page, login_page, home_page, loans_page, common_page):
    login_page.navigate()
    login_page.login("user1", "pass1")
    home_page.access_menu("Empréstimos")
    loans_page.choose_loan_amount("2.000,00")
    loans_page.click_take_out_loan()
    common_page.assert_text("A transação foi concluída com sucesso. Você pode voltar para a página principal e continuar suas operações.")
    common_page.return_to_home()
    common_page.assert_text("7.000,00")
    home_page.access_menu("Empréstimos")
    common_page.assert_text("Você já tem um empréstimo contratado em andamento. Novos empréstimos não estão disponíveis")